# Generated by Django 4.1 on 2024-06-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phonee",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
