# Generated by Django 4.1 on 2024-06-19 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 19, 14, 7, 26, 46061, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
