# Generated by Django 4.1 on 2024-06-19 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 19, 14, 8, 28, 478000, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
