# Generated by Django 4.1 on 2024-07-02 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 2, 0, 40, 41, 840929, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
