# Generated by Django 4.1 on 2024-07-08 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 8, 7, 35, 21, 780657, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
