# Generated by Django 4.1 on 2024-07-09 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 9, 10, 12, 56, 623250, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
