# Generated by Django 4.1 on 2024-07-09 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_blogarticles_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogarticles",
            name="publish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 9, 13, 1, 22, 564580, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
